### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by projectbridge** [hayesdavis/mockingbird#2]
I was wondering if there is a more recent version of this that works on the new twitter API, or if you think it would be reasonably doable to adapt this to work with the TweetStream gem. This is awesome and exactly what I'm looking for, except dated

**Comment by stve** [comment]
There's nothing Twitter API 1.1 specific about this gem, as the README states: 

> The server does not even pay attention to your actual request, it will just always respond with the defined configuration script regardless of what you send on connection.

**Comment by hayesdavis** [comment]
@projectbridge, as @spagalloco said, there's nothing really specific to any version of the Twitter API in this. It really is all in how you configure it. In fact, we've used it at our company to test streaming HTTP services that don't actually have anything to do with Twitter. That's one of the reasons why I haven't pushed out a new version. While I haven't personally used Twitter's public streaming APIs in quite some time, I would think the biggest limitation you would run into would be that Mockingbird doesn't currently support SSL. That probably wouldn't be too difficult to implement but I honestly haven't looked into it.

Check out the examples in the examples directory for different types of configurations. Also check out script.rb for the full configuration DSL. If you'd like to share a specific use case with me, I'll see if I can help you out with an appropriate configuration or if there really is a blocker.
