### ISSUE TITLE
Global drain for all connections

### ISSUE THREAD

**Issue by dreadjr** [hayesdavis/mockingbird#3]
I am trying to write something like this, but when each new connection comes in, each connection is sent elements 100-91.

I am trying to verify connection / reconnecting logic so I want to know I haven't missed any requests on the client.

I am probably just doing it completely wrong but thought i would reach out. thanks.

```
#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')
require 'mockingbird'

$cc = 1.step(100,1).to_a

Mockingbird.setup(:port=>8080) do

  on_connection(1..100) do
    10.times do
      c = $cc.pop
      send "[#{c}]\r\n"
      #send %Q({"foo":"bar-#{cc}"}\r\n)
      #print %Q({"foo":"bar-#{cc}"}\r\n)
      wait 0.5
    end
    #close
  end

end
```

**Comment by hayesdavis** [comment]
This is kind of tricky. The key is that the on_connection block isn't evaluated lazily on each connection. It's actually evaluated at setup time and "compiles" things into a series of commands that are run for the specified connections. So what this is actually doing is instructing the server to send the last 10 values from the $cc array with a 0.5s wait in between them to the first 100 connections that request them.

If you wanted to send one number in reverse order from the $cc array on each request, you'd need to do something like this:

``` ruby
$cc = 1.step(100,1).to_a

Mockingbird.setup(:port=>8080) do

  $cc.reverse.each_with_index do |c, i|
    on_connection(i+1) do
      send "[#{c}]\r\n"
      wait 0.5
      close
    end
  end

end
```

**Comment by dreadjr** [comment]
thanks a lot, that should work just fine.

**Comment by hayesdavis** [comment]
No problem, happy to help.
